---
- block:

  - name: 'metasploit : download installer'
    get_url:
      url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
      dest: /tmp/msfinstall
      mode: 0755

  - name: 'metasploit : run msfinstall'
    command: /tmp/msfinstall

  - name: 'metasploit : start postgresql'
    service:
      name: postgresql
      state: started

  - name: 'metasploit : create config directory'
    file:
      path: /usr/share/metasploit-framework/config
      state: directory

  - name: 'metasploit : create msf4 directory'
    file:
      path: /root/.msf4
      state: directory

    # The Kali version of msfdb needs to be run to allow for a
    # system wide configuration to be generated.
  - name: 'metasploit : run msfdb (kali version)'
    command: 'bash -lc "/opt/metasploit-framework/embedded/framework/msfdb-kali init"'
    register: msfdb
    failed_when: msfdb.rc != 10 and msfdb.rc != 0

  - name: 'metasploit : create symlink to system config'
    file:
      path: /root/.msf4/database.yml
      src: /usr/share/metasploit-framework/config/database.yml
      state: link

  - name: 'metasploit : stop postgresql'
    service:
      name: postgresql
      state: stopped

  - name: 'metasploit : cleanup temporary files'
    file:
      path: /tmp/msfinstall
      state: absent

  - name: 'metasploit : add alias to launch postgres with msfconsole'
    lineinfile:
      path: /root/.zshrc
      line: 'alias msfconsole="systemctl start postgresql && msfconsole"'

  - name: 'metasploit : create directory for tool wrappers'
    file:
      path: /usr/share/metasploit-framework/tools/exploit
      state: directory

  - name: 'metasploit : add wrapper for exploit tools'
    template:
      dest: /usr/share/metasploit-framework/tools/exploit/{{ item }}
      mode: 0755
      src: ../templates/msf_ruby_wrapper.sh
    with_items:
      - egghunter
      - exe2vba
      - exe2vbs
      - find_badchars
      - java_deserializer
      - jsobfu
      - metasm_shell
      - msf_irb_shell
      - msu_finder
      - nasm_shell
      - pattern_create
      - pattern_offset
      - pdf2xdp
      - psexec
      - random_compile_c
      - reg
      - virustotal

  tags:
    - exploitation
    - metasploit
